---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-promtail-tenant-0
data:
  promtail.yaml:  |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    client:
      url: http://loki:3101/api/prom/push
      basic_auth:
        username: Grafana
        password: L0k1
    scrape_configs:
      - job_name: sidecar-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: sidecar-logs
              __path__: /dir/shared/*
---
apiVersion: v1
kind: Pod
metadata:
  name: counter-tenant-0
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  - name: promtail-config
    configMap:
      name: loki-promtail-tenant-0
  containers:
  - name: count
    image: busybox
    volumeMounts:
    - name: shared-data
      mountPath: /dir/shared
    args: [/bin/sh, -c,
            'i=0; while true; do echo "My Log at tenant-0 $i: $(date)" >> /dir/shared/log; i=$((i+1)); sleep 1; done']
  - name: promtail
    args:
      - -config.file=/etc/promtail/promtail.yaml
    image: grafana/promtail:v0.3.0
    volumeMounts:
    - name: shared-data
      mountPath: /dir/shared
    - name: promtail-config
      mountPath: /etc/promtail
