---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kail-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: kail
  namespace: tenant-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kail
spec:
  selector:
    matchLabels:
      app: kail
      kail.ignore: "true"
  replicas: 1
  template:
    metadata:
      labels:
        app: kail
        kail.ignore: "true"
    spec:
      serviceAccount: kail
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: promtail-config
        configMap:
          name: loki-promtail-tenant-2
      containers:
      - name: kail
        image: angelbarrera92/kail:0.12
        args:
          - "/bin/sh"
          - "-c"
          - "kail --log-file /loki/logs/kail --log-level debug --ns tenant-2 >> /loki/logs/containers"
        volumeMounts:
        - name: shared-data
          mountPath: /loki/logs
        resources:
          requests:
            memory: "100Mi"
            cpu: "80m"
          limits:
            memory: "100Mi"
            cpu: "80m"
      - name: promtail
        args:
          - -config.file=/etc/promtail/promtail.yaml
        image: grafana/promtail:v0.4.0
        volumeMounts:
        - name: shared-data
          mountPath: /loki/logs
        - name: promtail-config
          mountPath: /etc/promtail
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-promtail-tenant-2
data:
  promtail.yaml:  |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    client:
      url: http://loki.logging.svc.cluster.local:3101/api/prom/push
      basic_auth:
        username: Tenant2
        password: 2tnaneT
    scrape_configs:
      - job_name: containers
        static_configs:
          - targets:
              - localhost
            labels:
              job: containers
              __path__: /loki/logs/containers
        pipeline_stages:
        - regex:
            expression: '^(?P<namespace>.*)\/(?P<pod>.*)\[(?P<container>.*)\]: (?P<content>.*)'
        - labels:
            namespace:
            pod:
            container:
        - output:
            source: content
      - job_name: kail
        static_configs:
          - targets:
              - localhost
            labels:
              job: kail
              __path__: /loki/logs/kail
        pipeline_stages:
        - regex:
            expression: '^time="(?P<time>.*)" level=(?P<level>.*) msg="(?P<content>.*)" cmp=(?P<component>.*)'
        - labels:
            time:
            level:
            component:
        - timestamp:
            source: time
            format: RFC3339
        - output:
            source: content
---
apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
    resources:
      requests:
        memory: "28Mi"
        cpu: "20m"
      limits:
        memory: "28Mi"
        cpu: "20m"
---
apiVersion: v1
kind: Pod
metadata:
  name: counter-2
spec:
  containers:
  - name: count-2
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$(date)"; i=$((i+1)); sleep 1; done']
    resources:
      requests:
        memory: "28Mi"
        cpu: "20m"
      limits:
        memory: "28Mi"
        cpu: "20m"
